#' OSM Tagging Proposals Data
#'
#' A data frame with `r nrow(proposals)` rows and `r ncol(proposals)` columns, containing all
#' Approved, Rejected and Proposed tagging proposals from the [OSM Wiki](https://wiki.openstreetmap.org), as well as their associated metadata.
#' This dataset has been created by the function `get_tagging_proposals()`
#' ran from the script `data-raw/tagging_proposals.R`.
#'
#' This documentation is not yet complete: lacks all the final fields from the dataset.
#'
#' @format
#'
#' columns:
#' \describe{
#'   \item{status}{a factor describing the proposal status: Approved, Rejected or Proposed.}
#'   \item{title}{a string with the wiki page containing the proposal}
#'   \item{sortkeyprefix}{a string}
#'   \item{timestamp}{a date and time. Not sure what which refers to. DELETE?}
#'   \item{pagelanguage}{a factor with the page's language. NOT WORKING, ALWAYS ENGLISH AND IT IS NOT TRUE. FIND ALTERNATIVE WAYS OF RETRIEVING THIS}
#'   \item{touched}{a timestamp when the page was last touched}
#'   \item{length}{(integer) page's length, in bytes.}
#'   \item{fullurl}{(string) URL pointing to the proposal's page.}
#'   \item{editurl}{(string) the URL to edit the page.}
#'   \item{pageid}{(int) the page's ID.}
#'   \item{page_creator}{(factor) the username who created the page.}
#'   \item{date_of_page_creation}{(date) the date and time in which the page was created.}
#'   \item{latest_editor}{(factor) the username who last edited the page.}
#'   \item{date_of_latest_edit}{(date) the date and time in which the page was last updated.}
#'   \item{total_number_of_edits}{(integer) number of total times that the page has been edited.}
#'   \item{total_number_of_disctinct_authors}{(integer) number of distinct users who have edited the page.}
#'   \item{proposal_status}{(factor) status of a proposal.}
#'   \item{proposed_by}{a string containing the name of the user(s) making the proposal.}
#'   \item{tagging}{a string describing the proposed tagging scheme}
#'   \item{applies_to_node}{(Boolean) whether this tag applies to nodes or not.}
#'   \item{applies_to_way}{(Boolean) whether this tag applies to ways or not.}
#'   \item{applies_to_area}{(Boolean) whether this tag applies to areas or not.}
#'   \item{applies_to_relation}{(Boolean) whether this tag applies to relations or not.}
#'   \item{definition}{a string containing a a short definition of what the tagging proposal aims to describe.}
#'   \item{rendered_as}{a string describing how the tagg is/should be rendered in the map (if any).}
#'   \item{draft_started}{date in which the proposal draft started.}
#'   \item{rfc_start}{date in which Request For Comments (RFC) started.}
#'   \item{vote_start}{date in which the voting process started.}
#'   \item{vote_end}{date in which the voting process ended.}
#'
#' }
#'
#' @source <https://wiki.openstreetmap.org/wiki/Proposal_process>
"proposals"

#' OSM Tagging Proposals' votes Data
#'
#' A data frame with `r nrow(proposals_votes)` rows and `r ncol(proposals_votes)` columns, containing all
#' the votes cast for every tagging proposal in `proposals`, generated by `get_proposals_votes()`.
#'
#'
#' @format
#'
#' columns:
#' \describe{
#'   \item{url}{(string) the URL to the tagging proposal wiki page.}
#'   \item{votes_raw}{a string with the wiki page containing the proposal.}
#'   \item{vote}{(factor) vote type (approve, abstain, oppose).}
#'   \item{user}{(factor) voter's username}
#'
#' }
#'
#' @source <https://wiki.openstreetmap.org/wiki/Proposal_process#Voting>
"proposals_votes"
